### ISSUE TITLE
3.0 introduces AttributeError for python 3.9

### ISSUE THREAD

**Issue by etherops** [dropbox/mypy-protobuf#335]
The 3.0 release introduces the following error, but only for python version 3.9+

```
find ./ -iname '*.proto' -exec python -m grpc_tools.protoc -I./ --python_out=/tmp/foo --twirp_pumpkinpy_out=/tmp/foo --twirp_python_out=/tmp/foo --mypy_out=/tmp/foo '{}' ';'

Traceback (most recent call last):
  File "/tmp/foo/venv/bin/protoc-gen-mypy", line 5, in <module>
    from mypy_protobuf.main import main
  File "/tmp/foo/venv/lib/python3.9/site-packages/mypy_protobuf/main.py", line 26, in <module>
    from . import extensions_pb2
  File "/tmp/foo/venv/lib/python3.9/site-packages/mypy_protobuf/extensions_pb2.py", line 22, in <module>
    casttype = DESCRIPTOR.extensions_by_name['casttype']
AttributeError: 'NoneType' object has no attribute 'extensions_by_name'
--mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
```

```
pip list | grep proto
mypy-protobuf      3.1.0
protobuf           3.13.0
types-protobuf     3.19.0

python --version
Python 3.9.7
```

I have been able to verify that for our use case our 3.8 and 3.7 builds are still good.  3.9 works on versions below 3.0 of mypy-protobuf.

Thank you!

**Comment by nipunn1313** [comment]
Thanks for the report. We have testssuites that run across all these python3.9 versions, so what you're seeing is pretty curious. It may have something to do with a mismatch of protobuf versions - since v3.0 requires a newer version of protobuf than the one you're using in your venv.

This should be encoded in our setup.cfg so pip should be doing it automatically.
https://github.com/dropbox/mypy-protobuf/blob/main/setup.cfg#L18

`pip3 install --upgrade protobuf` should get you straightened up.
I'm still unclear as to how that wasn't happening automatically though.

Do you have a reason for using an older protobuf release?

**Comment by nipunn1313** [comment]
Again not 100% sure - I'm speculating here - so let me know if it doesn't line up

**Comment by nipunn1313** [comment]
Actually, realized you'll probably have to upgrade your protoc to be a newer version - not just `pip install protobuf`.

**Comment by nipunn1313** [comment]
https://github.com/dropbox/mypy-protobuf#requirements-to-run-mypy-protobuf - is the requirements for latest mypy-protobuf (3.1.0)

You can check the README at earlier tags to see what the requirements were for earlier versions of mypy-protobuf
![image](https://user-images.githubusercontent.com/1300387/149420836-6eea680d-db1e-4d71-bf27-2160dfc8ac48.png)

**Comment by etherops** [comment]
hi @nipunn1313  - thanks again for the prompt reply.  i found that another dependency was pinning `protobuf` to the older version and for an undiagnosed reason our resolver was not picking up the conflict.  upgrading protobuf resolved our issues, thank you!
